// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPorts() {
  return window['go']['main']['App']['GetPorts']();
}

export function GetReceiveData() {
  return window['go']['main']['App']['GetReceiveData']();
}

export function OpenSerialPort() {
  return window['go']['main']['App']['OpenSerialPort']();
}

export function SendData(arg1) {
  return window['go']['main']['App']['SendData'](arg1);
}

export function SerialClose() {
  return window['go']['main']['App']['SerialClose']();
}

export function SetDelimiter(arg1) {
  return window['go']['main']['App']['SetDelimiter'](arg1);
}

export function SetPortSetting(arg1) {
  return window['go']['main']['App']['SetPortSetting'](arg1);
}
